### ISSUE TITLE
omega.h: No such file or directory

### ISSUE THREAD

**Issue by lakshit07** [omega-hub/llenc#1]
I was interested in your ***llenc*** repository but on building it, I encountered the **error : omega.h: No such file or directory**. I searched the entire folder but could not find the header file. Could you please help me with the same?

**Comment by febret** [comment]
lllenc needs to be built as part of omegalib - how were you using it?
also, note that the GRID SDK is not publicly available anymore afaik (the included versions are a couple of years old). So, I can't guarantee this module will work with updated Quadro drivers (in fact I'd be surprised if it does)

**Comment by febret** [comment]
Actually I just saw there is something called the NVIDIA Capture SDK that appears to be the new version of the grid SDK ~ pretty cool! This code would need some rework to use this new SDK but it appears the APIs are similar.

https://developer.nvidia.com/capture-sdk
